### ISSUE TITLE
ScrollTabs with tab panes?

### ISSUE THREAD

**Issue by BigBoss64** [joshreed/jQuery-ScrollTabs#15]
Is it possible to have tab panes with the ScrollTabs? The only thing I've seen is just the actual tabs scrolling without any other content attached.

**Comment by joshreed** [comment]
You mean have them actually perform some form of action? If so then absolutely yes. Under the "Usage" section on the documentation page there's the "click_callback" option to tell it what to do when a tab is clicked. http://joshreed.github.io/jQuery-ScrollTabs/documentation.html

In the below example it is used to follow a link to a different page. But you can change it to do any javascript action that you'd like. Just make sure you have an attribute on the tab DOM object itself to tell your function whatever it "needs to know" in order to perform the appropriate action.

```  
    $('#tabSet').scrollTabs({
      scroll_distance: 350,
      scroll_duration: 350,
      left_arrow_size: 26,
      right_arrow_size: 26,
      click_callback: function(e){
        var val = $(this).attr('rel');
        if(val){
          window.location.href = val;
        }
      }
    });
```
