### ISSUE TITLE
Last tab in index is the default view

### ISSUE THREAD

**Issue by brentstrange** [joshreed/jQuery-ScrollTabs#9]
It would be a nice option if the last tab (far right) was the default viewed on load (instead of index 0). This applies when you have time ordered tabs to match a time ordered graph (oldest to current). Or is there an easy way to do this with Javascript that I'm missing?

**Comment by joshreed** [comment]
@brentstrange the selected tab can be set by simply adding the `tab_selected` class to the `span` or `li` representing tab you wish to be selected. This will ensure that it is selected upon page load.

Example:
````
    <div id="custom_style_container1">
      <div id="tabs6" class="style1">
        <span>First Tab</span>
        <span>Another Tab 2</span>
        <span>Another Tab 3</span>
        <span class="tab_selected">Another Tab 4</span>
      </div>
    </div>
````

Additionally if you wish to programmatically click, you can do so via JQuery/JavaScript, just ensure that you've initialized the scrollTabs instance first:

````
  // Note this will actually click on the "finisher" span, which consequently 
  // will select the adjacently last element in the tab list
  $('#tabs1 span:last').click()
````

Finally, you can after-the-fact add the `tab_selected` class to the appropriate tab as well. Though if you do so, I'd suggest also running the somewhat undocumented method `refreshFirstLast()` (from the resulting ScrollTabs instance object) so that if you are utilizing the right or left finishers, they would also be updated. Here's an example:

````
  var tabSet = $('#tab_set').scrollTabs();

  // Below you can use whatever selector you'd like to reference your tab of interest,
  // an ID or CLASS would likely make sense.
  $('#tab_set span:nth-child(2)').addClass('tab_selected');

  // Refreshes the first/last item logic for "finishers"
  tabSet.refreshFirstLast();
````

Hopefully among these options available, you can find what may work in your situation.
